import { REGISTERED_ANALYZER_RULES } from "../analyzer/rules";
import type { AnalyzerRule } from "../analyzer/rules/types";

export const POSTGRES_MIGRATION_RULE_IDS = {
  DROP_TABLE: "PGM001_DROP_TABLE",
  TRUNCATE_TABLE: "PGM002_TRUNCATE_TABLE",
  ALTER_TABLE_ACCESS_EXCLUSIVE_DEFAULT:
    "PGM010_ALTER_TABLE_ACCESS_EXCLUSIVE_DEFAULT",
  DROP_COLUMN: "PGM011_DROP_COLUMN",
  RENAME_TABLE_OR_COLUMN: "PGM012_RENAME_TABLE_OR_COLUMN",
  ALTER_COLUMN_TYPE_REWRITE: "PGM013_ALTER_COLUMN_TYPE_REWRITE",
  SET_NOT_NULL_SCAN: "PGM014_SET_NOT_NULL_SCAN",
  ADD_COLUMN_NOT_NULL_IMMEDIATE: "PGM015_ADD_COLUMN_NOT_NULL_IMMEDIATE",
  ADD_COLUMN_WITH_DEFAULT_VERSION_AWARE:
    "PGM016_ADD_COLUMN_WITH_DEFAULT_VERSION_AWARE",
  DROP_CONSTRAINT: "PGM017_DROP_CONSTRAINT",
  CREATE_INDEX_WITHOUT_CONCURRENTLY:
    "PGM020_CREATE_INDEX_WITHOUT_CONCURRENTLY",
  CREATE_INDEX_CONCURRENTLY_IN_TRANSACTION:
    "PGM021_CREATE_INDEX_CONCURRENTLY_IN_TRANSACTION",
  DROP_INDEX_WITHOUT_CONCURRENTLY: "PGM022_DROP_INDEX_WITHOUT_CONCURRENTLY",
  ADD_FOREIGN_KEY_WITHOUT_NOT_VALID:
    "PGM023_ADD_FOREIGN_KEY_WITHOUT_NOT_VALID",
  VALIDATE_CONSTRAINT_LOCK_CONTEXT:
    "PGM024_VALIDATE_CONSTRAINT_LOCK_CONTEXT",
  ADD_CHECK_WITHOUT_NOT_VALID: "PGM025_ADD_CHECK_WITHOUT_NOT_VALID",
  ADD_UNIQUE_OR_PRIMARY_KEY_DIRECTLY:
    "PGM026_ADD_UNIQUE_OR_PRIMARY_KEY_DIRECTLY",
  ADD_EXCLUSION_CONSTRAINT: "PGM027_ADD_EXCLUSION_CONSTRAINT",
  REINDEX_WITHOUT_CONCURRENTLY: "PGM028_REINDEX_WITHOUT_CONCURRENTLY",
  REFRESH_MATERIALIZED_VIEW_WITHOUT_CONCURRENTLY:
    "PGM029_REFRESH_MATERIALIZED_VIEW_WITHOUT_CONCURRENTLY",
  LONG_RUNNING_BACKFILL_IN_MIGRATION:
    "PGM030_LONG_RUNNING_BACKFILL_IN_MIGRATION",
  MISSING_LOCK_TIMEOUT: "PGM031_MISSING_LOCK_TIMEOUT",
  LOCK_TABLE_EXPLICIT: "PGM032_LOCK_TABLE_EXPLICIT",
  ENUM_VALUE_CHANGE: "PGM033_ENUM_VALUE_CHANGE",
  CREATE_TRIGGER_OR_ENABLE_TRIGGER:
    "PGM034_CREATE_TRIGGER_OR_ENABLE_TRIGGER",
  VACUUM_FULL_OR_CLUSTER: "PGM035_VACUUM_FULL_OR_CLUSTER",
  CREATE_EXTENSION: "PGM036_CREATE_EXTENSION",
  DROP_TYPE_OR_DROP_SCHEMA: "PGM037_DROP_TYPE_OR_DROP_SCHEMA",
  CREATE_TABLE_AS_SELECT: "PGM038_CREATE_TABLE_AS_SELECT",
  MULTIPLE_RISKY_DDL_IN_ONE_MIGRATION:
    "PGM039_MULTIPLE_RISKY_DDL_IN_ONE_MIGRATION",
} as const;

export const POSTGRES_MIGRATION_RULES =
  REGISTERED_ANALYZER_RULES satisfies readonly AnalyzerRule[];
